apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-loki
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators-redhat
    server: https://kubernetes.default.svc
  project: default
  source:
    path: operator-loki
    repoURL: https://github.com/taisyo7333/demo-gitops
    targetRevision: main